# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/master/Work/test_ethernet_ddr3_fifo/project_led.srcs/sources_1/ip/fifo_pre/fifo_pre.xci
# IP: The module: 'fifo_pre' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/master/Work/test_ethernet_ddr3_fifo/project_led.srcs/sources_1/ip/fifo_pre/fifo_pre.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_pre'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/Work/test_ethernet_ddr3_fifo/project_led.srcs/sources_1/ip/fifo_pre/fifo_pre_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_pre'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/Work/test_ethernet_ddr3_fifo/project_led.srcs/sources_1/ip/fifo_pre/fifo_pre_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_pre'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/master/Work/test_ethernet_ddr3_fifo/project_led.srcs/sources_1/ip/fifo_pre/fifo_pre.xci
# IP: The module: 'fifo_pre' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/master/Work/test_ethernet_ddr3_fifo/project_led.srcs/sources_1/ip/fifo_pre/fifo_pre.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_pre'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/Work/test_ethernet_ddr3_fifo/project_led.srcs/sources_1/ip/fifo_pre/fifo_pre_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_pre'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/Work/test_ethernet_ddr3_fifo/project_led.srcs/sources_1/ip/fifo_pre/fifo_pre_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_pre'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
